# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sleep as Android
email: info@urbandroid.org
description: >- # this means to ignore newlines until "baseurl:"
  Documentation site for Sleep as Android (a sleep tracking, sleep cycle Android app)
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: UrbandroidTeam

search_enabled: true
#color_scheme: 'dark'

debug: true

# Build settings
markdown: kramdown
theme: "just-the-docs"
# incremental: true
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-rushed-analytics
  # - jekyll-asciidoc

collections:
  faqs:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "faqs" # a collection in your site, in plural form
    values:
      layout: "default"

asciidoc: {}
asciidoctor:
  template_dir: _templates
  attributes:
    xrefstyle: full
    imagesdir: /assets/images
    iconsdir: '{imagesdir}/../icons'
    hardbreaks: true
    icons: ''
    icontype: svg
    page-liquid: true
    toc-title: 'On this page:'
    sectlinks: true
    source-highlighter: rouge
    sectnumlevels: 5
    numbered: true

jekyll_rushed_analytics:
  GoogleAnalytics4:                       # Add, if you want to track with Google Analytics
    measurement_id: G-VKHQZDBBL2          # Required - replace with your tracking id

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - template.adoc
  - README.md
  - deploy.sh
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
